services:
  terraform:
    image: hashicorp/terraform
    volumes:
      - ./certs:/certs
    environment:
      VAULT_ADDR: https://vault:8200
      VAULT_TOKEN: root
      VAULT_CACERT: /certs/ca-cert.pem
    command: -chdir=terraform apply -auto-approve -input=false
