configs:
  vault.hcl:
    content: |
      ui            = true
      cluster_addr  = "https://127.0.0.1:8201"
      api_addr      = "https://127.0.0.1:8200"

      listener "tcp" {
        address       = "0.0.0.0:8200"
        tls_cert_file = "/certs/vault-cert.pem"
        tls_key_file  = "/certs/vault-key.pem"
        tls_min_version = "tls13"
        tls_disable_client_certs = true
      }

      log_level = "Debug"

  init.sql:
    content: |
      CREATE TABLE IF NOT EXISTS numbers (id INTEGER PRIMARY KEY);
      INSERT INTO numbers (id) VALUES (1), (2), (3), (4), (5);

services:
  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./certs:/certs
    cap_add:
      - IPC_LOCK
    configs:
      - vault.hcl
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_LOG_LEVEL: debug
      # we reroute default dev listener to 8300 because it's unconfigurable
      # actual tcp listener with tls is in the config
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
    command: server -dev -config /vault.hcl
    healthcheck:
      test: >-
        VAULT_ADDR=https://127.0.0.1:8200
        VAULT_CACERT=/certs/ca-cert.pem
        vault status
      interval: 15s
      start_interval: 3s
      start_period: 10s
    depends_on:
      tf_certs:
        condition: service_completed_successfully
        # restart ignores `condition`, see https://github.com/docker/compose/issues/12098
        # restart: true

  tf_certs:
    extends:
      file: ./common.yml
      service: terraform
    volumes:
      - ./terraform/certs:/terraform

  tf_db_engine:
    extends:
      file: ./common.yml
      service: terraform
    volumes:
      - ./terraform/db_engine:/terraform
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy

  tf_pki:
    extends:
      file: ./common.yml
      service: terraform
    volumes:
      - ./terraform/pki:/terraform
    depends_on:
      vault:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dbtest
    ports:
      - "5432:5432"
    volumes:
      - ./certs:/certs
    configs:
      - source: init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    command: >-
      -c ssl=on
      -c ssl_cert_file=/certs/postgres-cert.pem
      -c ssl_key_file=/certs/postgres-key.pem
      -c log_connections=on
    healthcheck:
      test: psql -U admin -d dbtest -h localhost -c 'SELECT 1;'
      interval: 30s
      start_interval: 3s
      start_period: 30s
    depends_on:
      tf_pki:
        condition: service_completed_successfully

  app:
    build:
      context: ./app
    container_name: spring-app
    volumes:
      - ./certs:/certs
    environment:
      VAULT_ADDR: https://vault:8200
      VAULT_TOKEN: root
      CERTS_PATH: /certs
      DATABASE_HOST: postgres:5432
    ports:
      - 8080:8080
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 5s
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
      tf_db_engine:
        condition: service_completed_successfully

networks:
  default:
    driver: bridge

